#!/usr/bin/env bash
set -euo pipefail

BUILDKITE_METAHOOK_HOOKS_PATH="$(mktemp -d)"
export BUILDKITE_METAHOOK_HOOKS_PATH
env | sort --buffer-size=4M | grep "BUILDKITE_PLUGIN_METAHOOK" | uniq >"${BUILDKITE_METAHOOK_HOOKS_PATH}/vars"

if grep -E 'BUILDKITE_PLUGIN_METAHOOK_.+(\.BAT|\.CMD)=' "${BUILDKITE_METAHOOK_HOOKS_PATH}/vars"; then
  echo "Sorry, we had to remove Windows Batch file support in 0.4.0."
  echo "Please refer to https://github.com/improbable-eng/metahook-buildkite-plugin/tree/master/changelog.md#0.4.0"
  echo ""
  exit 1
fi

"${BASH_SOURCE%/*}/run-hook.sh" "$(basename "${BASH_SOURCE[0]}")"
