#!/usr/local/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/stdlib.bash" || exit 67

cleanup() {
  rm -rf "${BUILDKITE_METAHOOK_HOOKS_PATH}"
}
trap cleanup EXIT

run_hook_when_needed "$(basename "${BASH_SOURCE[0]}")"
